### PR TITLE
fix for the issue of merging of nested rows

### PR DESCRIPTION
**Pull request by TermeHansen**
*Issue number of the reported bug or feature request: #459*

**Describe your changes**
Fix for the issue when merging row headers in nested indexes

**Testing performed**
Using the case from https://github.com/bloomberg/ipydatagrid/blob/0354a4d66c5c1298895026cec7d99bdb360914c1/examples/Nested%20Hierarchies.ipynb#L33

but changing top and bottom row and adding an extra element:

```
row_bottom_level = ["Sector 1", "Sector 1", "Sector 2", "Sector 2", "Sector 2"]
row_top_level = ["Security A", "Security B", "Security C", "Security C", "Security D"]

```

Current code gives:
image

Fixed code gives:
image

### CODE REVIEW

**Review by martinRenou — COMMENTED** [review]
Thanks a lot for this!

Would you be able to add a test notebook under `ui-tests-ipw8/tests/notebooks` to test this?

Also you need to signoff your commits. You can signoff using `git commit --signoff`, this also work in combination with `--amend` to modify your existing commits.

**Comment by martinRenou** [comment]
Thanks @TermeHansen ! If you want I can push another commit to your branch to get the CI green

**Comment by TermeHansen** [comment]
@martinRenou sure, whatever gets this in :smile:

**Comment by martinRenou** [comment]
I'll just get your visual regression test to pass, won't touch the rest of your code, thanks!

**Review by martinRenou — APPROVED** [review]

**Pull request merged**
