### PR TITLE
Add Galata tests

### PR DESCRIPTION
**Pull request by ibdafna**
Signed-off-by: Itay Dafna <idafna@seas.upenn.edu>

### CODE REVIEW

**Comment by ibdafna** [comment]
update galata references

**Comment by martinRenou** [comment]
update galata references

**Comment by martinRenou** [comment]
Triggering CI

**Review by martinRenou — DISMISSED** [review]
Looks good!

**Comment by ibdafna** [comment]
update galata references

**Review by martinRenou — APPROVED** [review]

**Pull request merged**
