### PR TITLE
Fix bot

### PR DESCRIPTION
**Pull request by martinRenou**
Fixes vulnerability

https://github.com/jupyterlab/extension-cookiecutter-ts/security/advisories/GHSA-rc7c-v5qg-g3vw

### CODE REVIEW

**Comment by martinRenou** [comment]
@gaborbernat pretty please! This fixes a vulnerability on our CI

**Comment by martinRenou** [comment]
Looks like I've been removed from the maintainers of ipydatagrid and lost rights

**Comment by martinRenou** [comment]
@kaiayoung

**Comment by gaborbernat** [comment]
Me too 😀

**Comment by martinRenou** [comment]
It seems I got some rights back, can you check on your side @gaborbernat ?

**Review by gaborbernat — APPROVED** [review]

**Comment by martinRenou** [comment]
Thanks for the review, we both have rights back!

**Pull request merged**
