### PR TITLE
Add logic for handling row transforms when row merging is applied

### PR DESCRIPTION
**Pull request by ibdafna**
Signed-off-by: Itay Dafna <idafna@seas.upenn.edu>

This PR disables any visual nested hierarchies *on the row level* when any transforms such as *filter* or *sort* are applied. It also fixes a bug (thanks @martinRenou for catching this!) where hierarchy validation for row-based groups was not applied correctly.

Code below used for testing:

```python
import pandas as pd
import ipydatagrid as ipdg

df = pd.DataFrame([
    ['A', 'aaa', 3],
    ['A', 'bbb', 2],
    ['B', 'aaa', 0],
    ['B', 'aaa', 1],
    ['B', 'aaa', 4],
], columns=['col1', 'col2', 'col3']).set_index(['col1', 'col2'])

g = ipdg.DataGrid(df, layout={"height":"140px"})
g```

### CODE REVIEW

**Comment by ibdafna** [comment]
Will add visual regression tests shortly.

**Comment by ibdafna** [comment]
@martinRenou Here is a weird case:
image

Do we want to support something like that? We do not allow this on for columns. I would think that there should always be a line that divides the lower level (group 'bbb') based on the parent groups (the line between 'A' and 'B'). What do you think?

**Comment by ibdafna** [comment]
@retadlock would appreciate any feedback on hierarchy verification logic. Going through the data path in your head can be a bit of a mind bend so do let me know if you need any clarifications. Thanks!

**Comment by retadlock** [comment]
> @retadlock would appreciate any feedback on hierarchy verification logic. Going through the data path in your head can be a bit of a mind bend so do let me know if you need any clarifications. Thanks!

Yup, bent my mind.  :)  I believe I see what you're doing and don't see a better way off the top of my (bent) mind, but let's go over this together tomorrow.

**Pull request closed without merging**
