### PR TITLE
Release 1.0.0

### PR DESCRIPTION
**Pull request by ibdafna**
Release version 1.0.0

### CODE REVIEW

**Review by mbektasbbg — APPROVED** [review]
LGTM!

**Review by gaborbernat — APPROVED** [review]

**Review by gaborbernat — CHANGES_REQUESTED** [review]
You need to sign-off your commits, see https://probot.github.io/apps/dco/

Please amend your commits accordingly and force push 👍🏻

**Comment by gaborbernat** [comment]
@ibdafna can we please do rebase instead of merge?

**Review by gaborbernat — APPROVED** [review]

**Pull request merged**
