### PR TITLE
🐛 Handle column auto fit on data model change

### PR DESCRIPTION
**Pull request by ollyhensby**
*Issue number of the reported bug or feature request: #451*

**Describe your changes**
When `data-model-changed` is triggered, call the `handleColumnAutoFit` method.

**Testing performed**
Tested that the script shown in the issue runs as planned:

```python
from ipydatagrid import DataGrid
import pandas as pd

df = pd.DataFrame([{"An Important Title": 1}])

grid = DataGrid(df, auto_fit_columns=True, layout={"height": "50px"})
display(grid)

df = pd.DataFrame([{"An Important Title": 1, "Another Title": 2}])
grid.data = df
```

When setting new data, the columns are now auto fit as expected.

### CODE REVIEW

**Comment by ollyhensby** [comment]
Looks like the `dark-datagrid-nested-hierarchies-update-ipynb-cell-5` and `light-datagrid-nested-hierarchies-update-ipynb-cell-5` are failing when comparing snapshots. Not 100% sure why as I ran the notebook locally and they seem to look the exact same? Maybe I am missing something?

**Comment by ollyhensby** [comment]
Hi @martinRenou, would you mind taking a quick look at this?

I've just merged the current main branch into my branch and the actions `jest / build (20.x)` and `check / visual-regression-tests-ipw7` are now failing with:

```bash
YN0028: The lockfile would have been modified by this install, which is explicitly forbidden.
```

**Comment by vthemelis** [comment]
It seems like your changer causes visual regressions? Did you have a look at the updated images?

**Comment by ollyhensby** [comment]
> It seems like your changer causes visual regressions? Did you have a look at the updated images?

Hi @vthemelis, thanks for taking the time to look at this.

I have updated the Galata images within this pull request to reflect the changes I've made and ensured the Galata tests pass successfully.

However, two of the Github checks are failing when it tries to install with yarn and I am not sure why that is the case. See my previous comment for the error that is returned.

**Comment by alkment** [comment]
@vthemelis any idea why the tests are failing. The PR does not introduce any changes to the dependencies/yarn. Would be great if this could make it's way into master and the next release.

**Review by gaborbernat — APPROVED** [review]

**Pull request merged**
