### PR TITLE
Make sure ipydguuid is removed in data getter

### PR DESCRIPTION
**Pull request by martinRenou**
In ipydatagrid <1.3, only the user dataframe columns would show up in the data accessor: 

Screenshot from 2024-05-13 11-30-16

This has changed in ipydatagrid 1.3 and the internal "ipyguuid" column was leaking, this PR fixes it

### CODE REVIEW

**Comment by martinRenou** [comment]
@gaborbernat pretty please :D 

It would be great to make a patch release with this and other merged PRs

**Comment by gaborbernat** [comment]
Tests?

**Comment by martinRenou** [comment]
I believe only visual regression tests can catch this as it was the front-end that was leaking a new dataframe column

**Comment by martinRenou** [comment]
I will look into it

**Comment by martinRenou** [comment]
Done!

**Review by gaborbernat — APPROVED** [review]

**Pull request merged**
