### PR TITLE
Add HTML Renderer

### PR DESCRIPTION
**Pull request by gjmooney**
**Describe your changes**
Adds an HTML renderer. Users can input HTML strings as the value of the cell and the output will be rendered HTML.

pr_shot

**Testing performed**
Manual testing and added visual regression tests

### CODE REVIEW

**Comment by gjmooney** [comment]
Bot update galata references

**Comment by paddymul** [comment]
Out of curiosity, how do you think about security with allowing users to input raw HTML?  Are you thinking about any type of disclaimers?

**Comment by martinRenou** [comment]
> Bot update galata references

The bot does not seem obedient https://github.com/bloomberg/ipydatagrid/actions/runs/8204278156/job/22438628744 ...

> Out of curiosity, how do you think about security with allowing users to input raw HTML? Are you thinking about any type of disclaimers?

I guess it would be fair to say that we are not far from the HTML widget situation in ipywidgets. Users can technically already output any HTML they want in the Jupyter notebook. I can also think of the `IPython.display` HTML output.

**Review by martinRenou — APPROVED** [review]
Thanks!!

**Pull request merged**
